# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(Build.SourceBranchName).$(date:yyyyMMdd).$(rev:r)

trigger:
- feature/*

stages:
- stage: build
  displayName: Build
  jobs:  
  - template: azure-pipeline-template-build-jobs.yml
- stage: unit_test
  displayName: Unit Test
  dependsOn: build
  condition: succeeded()
  jobs:  
  - template: azure-pipeline-template-unittest-jobs.yml
- stage: deploy
  displayName: Deployment
  dependsOn: unit_test
  condition: succeeded()
  jobs:
  - template: azure-pipeline-template-deploy-jobs.yml