jobs:
  - job: build
    displayName: Build service
    pool:
      name: "Doitsu Technology Linux Pipeplies"
      vmImage: "Doitsu.Technology.Ubuntu.Agent"
    variables:
      buildConfiguration: "Release"
    steps:
      - template: "./azure-pipeline-template-transform-config-files-steps.yml"
      - template: "./azure-pipeline-template-build-all-steps.yml"
