# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
    - master
    
pool:
    name: 'Doitsu Technology Linux Pipeplies'
    vmImage: 'Doitsu.Technology.Ubuntu.Agent'

variables:
    buildConfiguration: 'Release'
    nugetSource: 'https://api.nuget.org/v3/index.json'
    nugetSourceUploadKey: 'oy2ol23knrvokxqctjdq45is63t6c3ae7chpue6eu4jidq'

steps:

- task: DotNetCoreCLI@2
  displayName: "Building Doitsu.Ecommerce.Core Process"
  inputs:
    command: 'build'
    projects: 'src/Doitsu.Ecommerce.Core/Doitsu.Ecommerce.Core.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Test Process"
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Packing Doitsu.Ecommerce.Core Process"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'src/Doitsu.Ecommerce.Core/Doitsu.Ecommerce.Core.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'push $(Build.ArtifactStagingDirectory)/**/*.nupkg --source $(nugetSource) --api-key $(nugetSourceUploadKey) --skip-duplicate'