jobs:
  - job: deploy
    dependsOn:
    - build
    displayName: Deploy Nuget
    pool:
      name: "Doitsu Technology Linux Pipeplies"
      vmImage: "Doitsu.Technology.Ubuntu.Agent"
    variables:
      buildConfiguration: "Release"
      secretBuilderEmail: "$(SECRET_BUILDER_EMAIL)"
      secretBuilderPat: "$(SECRET_BUILDER_PAT)"
      ConnectionStrings.EcommerceDbContext: "$(SECRET_CONNECTION_STRING)"
      DeliveryIntegration.Ghtk.ClientSecret: "$(SECRET_GHTK_TOKEN)"
      SmtpMailServerOptions.CredentialPassword: "$(SECRET_SMTP_CREDENTIAL_PASSWORD)"
    steps:
      - task: FileTransform@1
        displayName: "File Transform: appsettings.json"
        inputs:
          folderPath: "$(System.DefaultWorkingDirectory)"
          fileType: json
          targetFiles: "**/appsettings.json"
      - task: replacetokens@3
        inputs:
            rootDirectory: './'
            targetFiles: '**/*.config'
            encoding: 'auto'
            writeBOM: true
            actionOnMissing: 'warn'
            keepToken: false
            tokenPrefix: '#{'
            tokenSuffix: '}#'
            useLegacyPattern: false
            enableTelemetry: true 
      - task: DotNetCoreCLI@2
        displayName: "Packing Doitsu.Ecommerce.ApplicationCore Process"
        inputs:
          command: 'pack'
          packagesToPack: 'src/Doitsu.Ecommerce.ApplicationCore/Doitsu.Ecommerce.ApplicationCore.csproj'
          includesymbols: true
          includesource: true
          versioningScheme: 'off' 
      - task: DotNetCoreCLI@2
        displayName: "Packing Doitsu.Ecommerce.Infrastructure Process"
        inputs:
          command: "pack"
          packagesToPack: "src/Doitsu.Ecommerce.Infrastructure/Doitsu.Ecommerce.Infrastructure.csproj"
          includesymbols: true
          includesource: true
          versioningScheme: 'off' 
      - task: NuGetCommand@2
        inputs:
          command: "push"
          feedsToUse: "select"
          packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
          nuGetFeedType: "internal"
          publishVstsFeed: "Doitsu.Technology"
          versioningScheme: "off"
          allowPackageConflicts: true
