jobs:
  - job: deploy
    displayName: Deploy Nuget
    pool:
      name: "Doitsu Technology Linux Pipeplies"
      vmImage: "Doitsu.Technology.Ubuntu.Agent"
    variables:
      - template: './azure-pipeline-template-variables.yml'
    steps:
      - template: "./azure-pipeline-template-transform-config-files-steps.yml"
      - template: "./azure-pipeline-template-build-all-steps.yml"
      - template: "./azure-pipeline-template-packing-all-steps.yml"