steps:
  - task: FileTransform@1
    displayName: "File Transform: appsettings.json"
    inputs:
      folderPath: "$(System.DefaultWorkingDirectory)"
      fileType: json
      targetFiles: "**/appsettings.json"
  - task: replacetokens@3
    inputs:
      rootDirectory: "./"
      targetFiles: "**/*.config"
      encoding: "auto"
      writeBOM: true
      actionOnMissing: "warn"
      keepToken: false
      tokenPrefix: "#{"
      tokenSuffix: "}#"
      useLegacyPattern: false
      enableTelemetry: true
