jobs:
  - job: unit_test
    displayName: "Unit Test"
    pool:
      name: "Doitsu Technology Linux Pipeplies"
      vmImage: "Doitsu.Technology.Ubuntu.Agent"
    variables:
      - template: './azure-pipeline-template-variables.yml'
    steps:
      - template: "./azure-pipeline-template-transform-config-files-steps.yml"
      - task: DotNetCoreCLI@2
        displayName: "Test Process"
        inputs:
          command: test
          projects: "**/*Tests/*.csproj"
          arguments: "--configuration $(buildConfiguration)"
