variables:
  secretBuilderEmail: "$(SECRET_BUILDER_EMAIL)"
  secretBuilderPat: "$(SECRET_BUILDER_PAT)"
  ConnectionStrings.EcommerceDbContext: "$(SECRET_CONNECTION_STRING)"
  DeliveryIntegration.Ghtk.ClientSecret: "$(SECRET_GHTK_TOKEN)"
  SmtpMailServerOptions.CredentialPassword: "$(SECRET_SMTP_CREDENTIAL_PASSWORD)"
steps:
  - task: replacetokens@3
    inputs:
      rootDirectory: "./"
      targetFiles: "**/*.config"
      encoding: "auto"
      writeBOM: true
      actionOnMissing: "warn"
      keepToken: false
      tokenPrefix: "#{"
      tokenSuffix: "}#"
      useLegacyPattern: false
      enableTelemetry: true
