# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
    - master
    
pool:
    name: 'Doitsu Technology Linux Pipeplies'
    vmImage: 'Doitsu.Technology.Ubuntu.Agent'

variables:
    buildConfiguration: 'Release'
    nugetSource: 'https://api.nuget.org/v3/index.json'
    nugetSourceUploadKey: 'oy2n4dtgwfurr6p55kuays2vgh3n4afufg3tw2dyelen6y'

steps:
- task: DotNetCoreCLI@2
  displayName: "Building Doitsu.Service.Core Process"
  inputs:
    command: 'build'
    projects: 'src/Doitsu.Service.Core/Doitsu.Service.Core.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Building Doitsu.Ecommerce.Core.Abstraction Process"
  inputs:
    command: 'build'
    projects: 'src/Doitsu.Ecommerce.Core.Abstraction/Doitsu.Ecommerce.Core.Abstraction.csproj'
    arguments: '--configuration $(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: "Building Doitsu.Ecommerce.Core Process"
  inputs:
    command: 'build'
    projects: 'src/Doitsu.Ecommerce.Core/Doitsu.Ecommerce.Core.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Building Doitsu.Ecommerce.Core.DeliveryIntegration Process"
  inputs:
    command: 'build'
    projects: 'src/Doitsu.Ecommerce.Core.DeliveryIntegration/Doitsu.Ecommerce.Core.DeliveryIntegration.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Building Doitsu.Ecommerce.Core.SEO Process"
  inputs:
    command: 'build'
    projects: 'src/Doitsu.Ecommerce.Core.SEO/Doitsu.Ecommerce.Core.SEO.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Test Process"
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Packing Doitsu.Service.Core Process"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'src/Doitsu.Service.Core/Doitsu.Service.Core.csproj'
    nobuild: true
    versioningScheme: 'off'
    
- task: DotNetCoreCLI@2
  displayName: "Packing Doitsu.Ecommerce.Core.Abstraction Process"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'src/Doitsu.Ecommerce.Core.Abstraction/Doitsu.Ecommerce.Core.Abstraction.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: "Packing Doitsu.Ecommerce.Core Process"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'src/Doitsu.Ecommerce.Core/Doitsu.Ecommerce.Core.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: "Packing Doitsu.Ecommerce.Core.DeliveryIntegration Process"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'src/Doitsu.Ecommerce.Core.DeliveryIntegration/Doitsu.Ecommerce.Core.DeliveryIntegration.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: "Packing Doitsu.Ecommerce.Core.SEO Process"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'src/Doitsu.Ecommerce.Core.SEO/Doitsu.Ecommerce.Core.SEO.csproj'
    nobuild: true
    versioningScheme: 'off'
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'push $(Build.ArtifactStagingDirectory)/**/*.nupkg -Source $(nugetSource) -ApiKey $(nugetSourceUploadKey) -SkipDuplicate'